### ISSUE TITLE
Osoba odpowiedzialna za zgłoszenie

### ISSUE THREAD

**Issue by zaquncio** [edk-software/rejony-app#11]
Możliwość przypisania osoby odpowiedzialnej za zgłoszenie. 
Czat ze zgłoszeń na stronie głównej powinien pojawiać się tylko dla zgłoszeń przypisanych do zalogowanego użytkownika.

**Comment by duzymaju** [comment]
W którym momencie przypisujemy osobę odpowiedzialną za zgłoszenie? Przy rozpoczynaniu weryfikacji (tam nie ma żadnego formularza - trzeba byłoby zrobić go w postaci pop-upa), czy dopiero przy akceptacji? Rozumiem, że to jest kwestia dodania nowego pola "odpowiedzialny" obok pola "weryfikujący" i całkowicie niezależnie od niego? Jaki poziom uprawnień powinni posiadać użytkownicy, którzy mogliby być przypisani jako odpowiedzialni? Pod słowem "czat" masz na myśli "Najnowsze rozmowy w zgłoszeniach rejonów" na stronie głównej przestrzeni projektu? Czy poza wyświetlaniem czata osoba odpowiedzialna ma mieć jakieś inne szczególne uprawnienia w kontekście "swoich" zgłoszeń rejonów?

**Comment by zaquncio** [comment]
Cześć dokładnie tak. Możemy to zrobić na formularzu gdzie rozpoczynamy weryfikację, bądź w edycji zgłoszenia z poziomu projektu - nie wiem co będzie łatwiejsze do implementacji. Weryfikujący i zatwierdzający to mogą być dwie różne osoby. Weryfikującymi i zatwierdzającymi mogą być tylko członkowie projektu  za wyjątkiem roli wizytor. 
Czat/najnowsze rozmowy w zgłoszeniach rejonów mam na myśli: listę z przypisanych do mnie zgłoszeń i ostatnią wiadomość dla każdego z tych zgłoszonych rejonów, ta lista powinna zastąpić obecną listę "najnowsze wiadomości w zgłoszeniach". Dodatkowo na stronie projektu powinna pojawić się lista ze zgłoszeniami które są do nikogo nie przypisane. Poza czatem nie ma dodatkowych uprawnień dla osoby przypisanej.
Propozycja dashboardu projektu tutaj na trello: 01004 - Propozycja dashboardów rejonu, projektu, grupy

**Comment by duzymaju** [comment]
OK, biorę się za to i postaram się skończyć w tym tygodniu.

**Comment by duzymaju** [comment]
Dobra, po części gotowe w #32 - dziś postaram się zrobić z wiadomościami w oparciu o te przypisania. Dajcie tylko znać, jak ma nazywać się ten bloczek na pulpicie.

**Comment by zaquncio** [comment]
"Wiadomości w przypisanych zgłoszeniach"

**Comment by duzymaju** [comment]
OK, lista wiadomości na pulpicie projektu zrobiona (poprzednią listę tylko wykomentowałem w serwisach, żeby w razie czego można było do niej wrócić). Ostatnim elementem zadania jest lista zgłoszeń nieprzypisanych do żadnej osoby odpowiedzialnej - tyle że teraz osobę odpowiedzialną przypisuje się od razu przy rozpoczynaniu weryfikacji i jest to przypisanie obligatoryjne, więc nie będzie nowych zgłoszeń, które nie będą do nikogo przypisane. Czy w takim wypadku ma sens ta lista? A jeśli tak, czy trzeba też dorabiać w edycji zgłoszenia akcję zmiany osoby odpowiedzialnej?

**Comment by zaquncio** [comment]
@duzymaju w takim wypadku nie ma sensu robić listy nieprzypisanych zgłoszeń. Zobaczymy jak to się będzie sprawdzać najwyżej potem dorobimy edycję. Czy to jest gotowe do merge?

**Comment by duzymaju** [comment]
Tak, w mojej ocenie jest, choć może sprawdź to sobie na wszelki wypadek jeszcze przed - jak się przełączysz na branch, musisz zrobić sobie `doctrine:migrations:migrate`, a przed powrotem do mastera (jeśli chciałbyś zmienić bazę z powrotem na starą) - `doctrine:migrations:migrate 20171120123755`.
