### ISSUE TITLE
Możliwość podpinania linków do bazy materiałów

### ISSUE THREAD

**Issue by zaquncio** [edk-software/rejony-app#123]
Zamiast wgrywania pliku, wskazanie URL do pobrania.

**Comment by duzymaju** [comment]
Załatwione: https://github.com/edk-software/rejony-app/pull/128.

**Comment by zaquncio** [comment]
@duzymaju jak to jest  zrobione od strony mechanizmu, te pliki lądują fizycznie u nas, czy podczas pobierania jest to gdzieś przekierowywane?

**Comment by duzymaju** [comment]
Ląduje u nas, jeśli wstawisz plik, a nie link. Później dostęp do pliku też wymaga uprawnień (bo żądanie pobrania też przechodzi przez kontroler). Jeśli zależy nam na skalowaniu, trzeba to będzie przerobić, ale chyba i tak nie jesteśmy w stanie skalować się na wiele serwerów. Chyba że chodzi Ci o obciążenie aktualnego lub zawalenie go plikami?

**Comment by zaquncio** [comment]
Zazwyczaj jest tak że jako linki umieszczane są pliki nie obsługiwane przez
panel, albo o bardzo dużym rozmiarze.
Optymalnie byłoby, gdyby to był tylko link, a materiał pobierał się z
serwera na którym jest np. poprzez otwarcie w nowym oknie.

niedz., 17 mar 2019 o 10:16 Wiktor Maj <notifications@github.com>
napisał(a):

**Comment by duzymaju** [comment]
No to tak teraz też się da, po realizacji taska, którego dotyczy ta konwersacja (pull request #128), tyle że wtedy trzeba podać pełen link do materiału w zewnętrznym zasobie. Aplikacja po kliknięciu w "nasz" lokalny link robi przekierowanie 302 i użytkownik może pobrać plik. Jest OK?

**Comment by zaquncio** [comment]
Jeśli pliki podczas podania URL, nie są kopiowane na nasz serwer to jest ok.

pon., 18 mar 2019 o 15:28 Wiktor Maj <notifications@github.com> napisał(a):

**Comment by duzymaju** [comment]
Nie są.
