### ISSUE TITLE
brak możliwości rejestracji na trasę w rejonie 'Na wzór EDK'

### ISSUE THREAD

**Issue by quchasz** [edk-software/rejony-app#125]
W rejonie _Na wzór EDK_ gdzie mamy tylko jedną trasę na wzór nie działają zapisy, mimo że rejon jest **aktywny** oraz trasa jest **zatwierdzona**.

Rejon i trasa są widoczne na mapie.

Przy próbie rejestracji trasa nie jest wybierana automatycznie, nie można jej również znaleźć na liście tras (albo ja jej nie widzą).

Po zmianie rejonu z _Na wzór EDK_ na _Pełny rejon_ zapisy zaczynają działać.

Trasy których to dotyczy to między innymi:
https://www.edk.org.pl/trasa-edk/2303
https://www.edk.org.pl/trasa-edk/2330

**Comment by zaquncio** [comment]
@quchasz sprawdź proszę czy już jest ok

**Comment by quchasz** [comment]
@zaquncio 
- próba rejestracji po wybraniu rejonu/trasy z mapy: **OK**
- próba rejestracji po wybraniu rejonu/trasy z linka _Dołącz_: **OK**

obydwie rejestracje widoczne na trasie:
![Screen Shot 2019-03-08 at 23 35 55](https://user-images.githubusercontent.com/47346557/54059891-0e0f6f00-41fb-11e9-9241-a3fe30e94e53.png)
