### ISSUE TITLE
CAPTCHA rejestracja użytkownika

### ISSUE THREAD

**Issue by zaquncio** [edk-software/rejony-app#2]
Dodanie CAPTCHA w formie słowa do przepisania.

**Comment by duzymaju** [comment]
Czy zastosowana tam RECAPTCHA (była tam od dawna) jest OK, czy mam ją zmieniać?

**Comment by zaquncio** [comment]
W tym momencie jest RECAPTCHA w formularzu rejestracji uczestnika EDK (http://rejony.edk.org.pl/pub/edk/Eb2qrCBtKDlQ/zapisy/formularz?_locale=pl) wydaje mi się, że jest ok. Jeśli znasz jaką lepsza metodę to możemy zmienić, ale całościowo w aplikacji. W tym zadaniu chodzi o dodanie go w tym formularzu (/auth/register) - jakiś boot rejestrował się w poprzedniej edycji.
