### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by zaquncio** [edk-software/rejony-app#22]
Moduł pytań i odpowiedzi. Możliwość przypisania taga do pytania. W zestawieniu filtrowanie po tagu + wyszukiwanie.

**Comment by zaquncio** [comment]
@duzymaju w wolnej chwili przenieś bundla do przestrzeni cantigi pozwoli nam to na późniejszą integrację tego rozwiązania z bundlem milestone.

**Comment by duzymaju** [comment]
@zaquncio: O jakim bundle'u mówisz?

**Comment by zaquncio** [comment]
Utwórzmy z FAQ i materiałów osobny bundle i przenieśmy go do przestrzeni cantigi (obecnie jest w WIO). Docelowo do bundla milestone będzie można likować pytania z FAQ i materiały z materiałów (temat na przyszły rok). @duzymaju co myślisz?

**Comment by duzymaju** [comment]
Spoko - przeniosę to tam (jak skończę z #11) i stworzę od razu #23.

**Comment by duzymaju** [comment]
OK, przeniesione - do zrobienia pozostaje panel administracyjny, za który będę się brał.

**Comment by duzymaju** [comment]
Panel gotowy - zrobiłem merge'a przed chwilą. Zamykam więc. :)

**Comment by zaquncio** [comment]
@duzymaju Dzięki!
