### ISSUE TITLE
Baza materiałów

### ISSUE THREAD

**Issue by zaquncio** [edk-software/rejony-app#23]
Baza plików z poziomem dostępu w przestrzeni projektu, jak i dla wszystkich, Możliwość tagowania plików.

**Comment by duzymaju** [comment]
Czy możemy zrobić to analogicznie do FAQ, czyli grupowanie plików w kategorie, dostęp dla poszczególnych poziomów uprawnień i podobna (choć nie "rozwijalna") podstrona w panelu? Jeśli tak, skopiowałbym po prostu tabele z bazy.

**Comment by zaquncio** [comment]
Myślę, że tak. Tutaj fajnie jakby się pojawiła możliwość dodawania materiałów z poziomu projektu i ewentualnej zmiany ich widoczności. Czy aktualnie jest tak, że wszystko to co widzi rejon jest widoczne w grupie i projekcie? Zależy mi aby nie dublować rzeczy i utrzymywać zmian np. w kilku miejscach.

**Comment by duzymaju** [comment]
Tak, w FAQ dla danego pytania określany jest najniższy poziom uprawnień, co powoduje, że pytania wyświetlane od przestrzeni rejonu wyświetlane są też w grupie i projekcie. Do FAQ dokończę oczywiście robić panel administracyjny, jak będzie trochę czasu - analogiczny panel będzie do plików, tyle że z możliwością ich zapisu na dysku.

**Comment by zaquncio** [comment]
@duzymaju przez dysk rozumiesz przestrzeń na serwerze?

**Comment by duzymaju** [comment]
Tak, dokładnie - na razie byłby to folder w tej lokalizacji, w której leżą pliki projektu, a jeśli będzie kiedyś taka potrzeba, można będzie zastanowić się nad przeniesieniem tego gdzieś na zewnątrz (w chmurę?).

Baza materiałów (na razie analogicznie jak FAQ bez panelu administracyjnego) gotowa: #33 - klepnijcie to, proszę, a ja zrobię merge'a.

**Comment by duzymaju** [comment]
OK, scalone - do zrobienia pozostaje panel administracyjny, za który będę się brał.

**Comment by zaquncio** [comment]
@duzymaju czy jest możliwe, aby pobierane pliki miały jakąś przyjazną nazwę? Najlepiej oryginalną, bądź nazwę z bazy.

**Comment by duzymaju** [comment]
Jasne - już to zrobiłem i pchnąłem do `master`a - teraz nazwą pliku będzie slug nazwy z bazy, a jeśli ta nazwa się powtórzy, do drugiego i kolejnych plików będzie dodawany sufiks `-n`, gdzie `n` to kolejne liczby poczynając od 2.
