### ISSUE TITLE
CAPTCHA w formularzu wyrejestrowania

### ISSUE THREAD

**Issue by zaquncio** [edk-software/rejony-app#3]
Dodanie zabezpieczenie w ekranie usunięcia zgłoszenia uczestnictwa w EDK.

**Comment by duzymaju** [comment]
Jak nazywa się ta akcja albo jaką ma ścieżkę (URL)?

**Comment by zaquncio** [comment]
przed wywołaniem tych metod:
src/WIO/EdkBundle/Controller/PublicRegistrationFormController.php
private function removeRequest($key)
