### ISSUE TITLE
Automatyczna weryfikacja poprawności śladu

### ISSUE THREAD

**Issue by zaquncio** [edk-software/rejony-app#5]
Weryfikacja śladu pod względem:
- długość
- przewyższenia
- ciągłość śladu
- kolejność stacji
- numeracja stacji
Dodatkowo na podstawie tych kryteriów powinna pojawić się informacja, czy trasa jest pełna, czy na wzór.

**Comment by qooban** [comment]
@zaquncio Na wyjeździe rozmawiałem z Romkiem, który testował weryfikator i sugerował dodanie bardziej precyzyjnych informacji na temat tego co poszło nie tak w weryfikacji (np. która stacja jest w niewłaściwej kolejności, jaka nazwa jest niepoprawna, itp.). Pamiętam, że kiedyś o tym rozmawialiśmy. Proponowałem wtedy raport wynikowy z weryfikacji. Może warto byłoby do tego wrócić? Z mojej perspektywy, to byłaby praca nad dopasowaniem informacji, którą i tak już gromadze (wszystkie sprawdzenia i błędy są logowane). 

Temat (+ opis dwóch możliwych rozwiązań) zarejestrowałem tutaj: https://github.com/qooban/edk-route-verifier/issues/34 .

Moja pełna lista TODO jest tutaj: https://github.com/qooban/edk-route-verifier/issues

Chciałbym, żeby Marcin Piekarz i Romek pomogli mi w przygotowaniu automatów (na razie mam dwa KMLe do weryfikacji). Jak to będzie, to mamy dużo większe pole do wprowadzania szybkich i bezpiecznych zmian.
