### ISSUE TITLE
Przeładownie widoku trasy po automatycznym zatwierdzeniu

### ISSUE THREAD

**Issue by zaquncio** [edk-software/rejony-app#61]
Trasa się zatwierdza, ale na podglądzie trasy dalej jest status nie zatwierdzona.

**Comment by zaquncio** [comment]
@duzymaju dasz radę?

**Comment by duzymaju** [comment]
Jasne. Wyślij mi tylko screena, o jaki podgląd chodzi, bo nadal nie znam tego systemu w 100%. :)

**Comment by zaquncio** [comment]
![image](https://user-images.githubusercontent.com/5955357/36027015-c73e4df8-0d99-11e8-8f8a-9bcc447fd258.png)
Chodzi o to aby, po strzale do api o weryfikacji strona się przeładowała.
Kuba:
w elemencie: div id="map-canvas"
jest taki atrybut: data-route-approve="{{ spath('edk_route_approve', {'id': item.id}) }}?answer=yes">
i to tam (edk_route_approve) jest wykonywany strzał, jeśli wszystkie weryfikacje przeszły poprawne.

**Comment by duzymaju** [comment]
#75

**Comment by duzymaju** [comment]
@qooban: To jest już do zamknięcia, prawda?

**Comment by qooban** [comment]
@duzymaju: Tak, do zamknięcia.
