### ISSUE TITLE
Przyjazna nazwa pliku pobieranego z materiałów

### ISSUE THREAD

**Issue by zaquncio** [edk-software/rejony-app#73]
Nazwa nie powinna być guidem, ale nazwą która powie coś użytkownikow

**Comment by duzymaju** [comment]
Problem powinien być już rozwiązany - 28 stycznia w commicie `efe9817` w `AdminMaterialsFileController` dodałem tworzenie nazwy na podstawie podanej w formularzu nazwy pliku. Sprawdź proszę i jeśli jest OK, zamknij ten task - dzięki!
