### ISSUE TITLE
Błąd usuwania materiału

### ISSUE THREAD

**Issue by zaquncio** [edk-software/rejony-app#74]
Jeśli materiał podpięty jest do zadania, podczas usuwania leci błąd. Najprawdopodobniej nie obsłużony jest klucz obcy tabela: milestone_material

**Comment by duzymaju** [comment]
Dokładnie tak jest - po dodaniu klucza obcego do pliku w tabeli łączącej go z kamieniem milowym, zaczął lecieć błąd. Wszystko byłoby OK, gdyby Doctrine'owy ORM obejmował całą bazę ale na razie struktura zadeklarowana jest tylko w KnowledgeBundle. Jeśli problem jest pilny, po prostu w MilestoneBundle dorobię wieczorem metodę usuwającą rekord i będę ją wywoływał w KnowledgeBundle przed usunięciem pliku (bo rozumiem, że rekord z `milestone_material` trzeba wywalić), natomiast jeśli to tylko nieistotny bug, wolałbym dodać YAMLe z opisami wszystkich tabel - wtedy dowiązania będą obsługiwane z automatu, a przede wszystkim będzie można robić diffy migracji - to zajęłoby mi jednak przynajmniej kilka dni. Daj znać, jeśli dziś będziesz to czytał.

**Comment by zaquncio** [comment]
Może poczekać na po edycji.

**Comment by duzymaju** [comment]
Huh, a ja w międzyczasie już dorobiłem zmianę, więc można zamknąć, a jak dodamy pełen mapping Doctrine'owego ORMa, to usuniemy. ;)
