### ISSUE TITLE
Dodanie możliwości przesłania uwag do trasy

### ISSUE THREAD

**Issue by zaquncio** [edk-software/rejony-app#84]
Uczestnik, powinien mieć możliwość przesłania uwag do trasy. Formularz powinien być publicznie dostępny (podobnie jak zgłoszenie, czy kontakt z rejonem). Zawierać powinien 4 pola (wybór lokalizacji, wybór rejonu, wybór trasy, komentarz). Wybór trasy odbywać się powinien analogicznie jak wybór trasy przy rejestracji, z tym że lista dostępnych powinna być brana na podstawie tras zatwierdzonych (apperved).

**Comment by zaquncio** [comment]
@duzymaju dasz radę zrobić to jeszcze przed EDK?

**Comment by duzymaju** [comment]
@zaquncio: Kurde, trochę mało czasu... Postaram się powalczyć ale nie chcę niczego obiecywać. :/

**Comment by zaquncio** [comment]
@duzymaju wybór jak na formularzy rejestracji. Lokalizacja to: polska: małopolskie, polska: wielkopolskie,... - pierwsze selectbox z formularza rejestracji uczestnika. Dzięki!

**Comment by duzymaju** [comment]
Dodałem #85.
