### ISSUE TITLE
Elektroniczne podpisywanie umów

### ISSUE THREAD

**Issue by zaquncio** [edk-software/rejony-app#90]
W ramach jednego projektu zdefiniowana powinna zostać lista umów możliwych do podpisania. Umowa składa się z: 1. Testu umowy (rtf lub html - co nam będzie wygodniej) 2. Daty wprowadzenia umowy do systemu 3. Treści akceptacji zgody (html).
Definiowanie umów odbywać się będzie z poziomu przestrzeni projektu w sekcji"Zarządzaj"
![image](https://user-images.githubusercontent.com/5955357/52502294-bcb39600-2be2-11e9-9360-eacf9fab50f8.png)
W ramach projektu każdy użytkownik będzie mógł podpisać kilka umów. Weryfikacja czy dane umowy zostały podpisane odbywać się będzie podczas wchodzenia w dashboard projektu, grupy, bądź rejony.
W przypadku braku zaakceptowania umowy system poprosi o wprowadzenie obowiązkowych danych takich jak: 1. Imię, 2. Nazwisko, 3. Miejsce zamieszkania: miejscowość, kod, ulica, numer domu, numer lokalu, 4. Pesel, 5. Data urodzenia, 6. Miejsce urodzenia. Wszystkie pola za wyjątkiem numeru lokalu są obowiązkowe. Poniżej wyświetlona zostanie umowa, wraz z checkiem zawierającym treść akceptacji zgody. Dodatkowo system zapisze w bazie danych daty akceptacji.
Przypisanie umów koniecznych do zaakceptowania odbywać się będzie poprzez edycję profilu użytkownika:
![image](https://user-images.githubusercontent.com/5955357/52502823-02249300-2be4-11e9-9330-fc7ed8ad3874.png)
![image](https://user-images.githubusercontent.com/5955357/52503169-0604e500-2be5-11e9-8f5e-3f10769d79b5.png)

**Comment by duzymaju** [comment]
W branchu `feature/#90-agreements` dodałem na razie podstawową funkcjonalność (akceptację umów przez użytkownika w dashboardach) bez layoutu - @zaquncio zobacz proszę, czy ma to działać w taki sposób (jeśli są jakieś niezaakceptowane umowy dla danego użytkownika w danym projekcie, pokazują się w dashboardzie projektu i dashboardach potomnych i są obowiązkowe do zatwierdzenia, jeśli chce się zobaczyć właściwy dashboard - wyświetlają się tytuły, treści i/lub linki do umów razem z checkboxami przy treściach akceptacji umów, a poniżej formularz z danymi osobowymi, ew. uzupełniony danymi użytkownika, jeśli wcześniej zatwierdzał jakieś umowy gdziekolwiek), a ja robię dodawanie potrzeby akceptacji umów w profilu użytkownika.

**Comment by duzymaju** [comment]
Dodałem rozszerzenie do profilu członka społeczności (zgodnie ze screenem powyżej). Do dodania jest polskie tłumaczenie i ew. stylowanie, tylko najpierw proszę (@zaquncio) o przeklikanie się przez to (branch `feature/#90-agreements`) i informację, czy działa tak, jak miało w zamyśle.
W tym tygodniu nie dam rady zrobić już panelu definiowania umów ale tak, jak rozmawialiśmy, to jest najmniej pilne.
Ważne pytanie - czy każda osoba, która widzi profil członka społeczności ma mieć możliwość zarządzania tym, czy użytkownik ma, czy nie ma podpisywać umów? Jeśli nie, trzeba zrobić jeszcze kontrolę dostępu - daj proszę znać.

**Comment by duzymaju** [comment]
Dziś mi przyszło do głowy, czy rzeczywiście data urodzenia jako osobne pole jest potrzebna, bo ta informacja zawarta jest w numerze PESEL, który pobieramy? Dodatkowo możemy zawęzić wielk użytkownika właśnie po numerze PESEL (np. dopuszczać tylko osoby pełnoletnie w danej chwili). Co Ty na to @zaquncio?

**Comment by zaquncio** [comment]
ok

**Comment by duzymaju** [comment]
Dodałem panel do obsługi umów (ostatni element układanki), a dodatkowo zrobiłem to, o co pytałem - usunąłem pole "data urodzenia" i wyciągam ją z numeru PESEL, sprawdzając przy okazji, czy użytkownik ma co najmniej 18 lat w czasie podpisywania umowy.
Proszę o testy całości (szczególnie w kwestii uprawnień, bo w tym, kto co tu może, biegły nie jestem) i wdrażamy. :)
